### ISSUE TITLE
Unable to submit to AppStore due to strip-frameworks.sh signature

### ISSUE THREAD

**Issue by andreamazz** [realm/realm-cocoa#1865]
Hi all. 
I'm, trying to Archive and submit an app that is using Realm as a dynamic framework (due to an issue with cocoapods, frameworks and extensions it's my only option right now).  

iTunes validation fails with this message: 
**The binary at path [Gulps.app/Frameworks/Realm.framework/strip-frameworks.sh] contains an invalid signature**
![screen shot 2015-05-07 at 18 40 30](https://cloud.githubusercontent.com/assets/570797/7520744/36392308-f4e9-11e4-8812-0c95d3ddac3a.png)

I'm currently using 0.92.1 with Xcode 6.3.1.

**Comment by andreamazz** [comment]
I did work around this by adding 
```
rm ${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh
```
to the build phase script :sweat_smile: 
I don't know if this is the best way to do this though.

**Comment by jimjeffers** [comment]
@segiddins Not sure what the fix was here. I'm getting this on 0.92.3 now. Is the fix simply amending the build phase script as andreamazz did or should this be resolved in the current build?

**Comment by andreamazz** [comment]
@jimjeffers it should be resolved, the build script `strip-frameworks.sh` is no longer executable, so Xcode shouldn't complain.

**Comment by webmagnets** [comment]
This isn't resolved for me. I have the latest RealmSwift installed, but I am still getting that error when trying to submit to the app store. Should I add ```rm ${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh```?

**Comment by andreamazz** [comment]
The latest `RealmSwift.framework` has the correct permissions on the strip-freamework script, so that's weird. Open a terminal, go into your copy of `RealmSwift.framework/` and make sure that `strip-freamework.sh` is not executable. If it is, run `chmod -x strip-freamework.sh`

**Comment by webmagnets** [comment]
I ran ```chmod -x /Users/nathancain/Library/Developer/Xcode/DerivedData/Readmersion-eptpcuuyaiwxwxgcjybncfsqrxys/Build/Products/Debug-iphoneos/Readmersion.app/Frameworks/RealmSwift.framework/strip-frameworks.sh```. Does that seem like the correct directory?

If so, then that didn't fix the problem. I am adding some screen shots that shows the errors. I didn't realize until now that there are other errors if scroll down, so I am attaching two images here.

![screenshot 2015-05-24 05 51 38](https://cloud.githubusercontent.com/assets/1189875/7787713/0baf3a7e-01e0-11e5-8183-7d0b4a3cc648.png)
![screenshot 2015-05-24 05 52 20](https://cloud.githubusercontent.com/assets/1189875/7787714/0bc2f8ca-01e0-11e5-8fcf-f3e5f3112a9b.png)

**Comment by andreamazz** [comment]
No, you need to run it in the framework inside your project's folder, not on the derived data.

**Comment by webmagnets** [comment]
Ok, not I tried ```chmod -x /Users/nathancain/Documents/Readmersion/RealmSwift.framework/strip-frameworks.sh```, clean, build, archive, submit and it still gave me the same errors. Also please notice the "nested bundles" and the "disallowed file 'Frameworks'" errors.

Thanks for your help. I appreciate your work.

**Comment by andreamazz** [comment]
I see, this seems related to this issue https://github.com/realm/realm-cocoa/issues/1907 
Can you switch to a cocoapods install for the time being? That should take care of the problem (on the other hand, if you have extensions in your app, another problem might arise).

**Comment by andreamazz** [comment]
You can also try this: https://github.com/realm/realm-cocoa/pull/1942
You'll need to manually build until next release, but it should go through submission just fine.

**Comment by webmagnets** [comment]
How do you manually build?

**Comment by andreamazz** [comment]
```
git clone git@github.com:realm/realm-cocoa.git
cd realm-cocoa
git pull origin seg-package-swift
sh build.sh build
open build
```

**Comment by andreamazz** [comment]
Here's a build:
http://d.pr/f/8lq4

**Comment by andreamazz** [comment]
Sorry, just realized that I was working on the master branch :sweat_smile: 
Uploading a new build now

**Comment by webmagnets** [comment]
Were you planning on putting another dropbox link on here?

**Comment by andreamazz** [comment]
I'm having horrible upload speed at the moment, you can however run the commands above to build on your machine

**Comment by webmagnets** [comment]
I'm getting:

    Cloning into 'realm-cocoa'...
    Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.

**Comment by andreamazz** [comment]
Use the http endpoint instead
git clone https://github.com/realm/realm-cocoa.git

**Comment by webmagnets** [comment]
Ok, that worked. Now am I supposed to find the RealmSwift.framework and copy it into my project?

**Comment by andreamazz** [comment]
Yeah, you'll find the frameworks in the `build` folder

**Comment by webmagnets** [comment]
Submission worked!!! Thanks.

**Comment by andreamazz** [comment]
:+1:

**Comment by JhimliBora** [comment]
Hi, help needed.

was getting errors while submitting archive to iTunes using Realm Database version 0.93.2.
Tried manual build and copied both frameworks from build folder to my project folder.Archieve gets created but submission failing. getting following errors. What am I doing wrong?
![screen shot 2015-06-18 at 12 06 05 am](https://cloud.githubusercontent.com/assets/12937318/8209100/780b75ee-154e-11e5-9f7c-3307351d344d.png)

**Comment by JhimliBora** [comment]
Latest Xcode version is installed on my machine.

**Comment by JhimliBora** [comment]
Xcode Version is 6.3.2 and RealmSwift version 0.93.2

**Comment by segiddins** [comment]
@JhimliBora have you done step four of the installation instructions on https://realm.io/docs/swift/latest/, i.e. adding a run script build phase to call `bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh"` ?

**Comment by JhimliBora** [comment]
1) first I did all steps mentioned in the Realm Installation Document including bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Realm.framework/strip-frameworks.sh" 
It was failing while creating the Archive saying "....IamHappy.app/Frameworks/Realm.framework/strip-frameworks.sh:No such file or directory 

2) Next I found the above post and tried the manual step. copied both the frameworks from the build folder into my project folder.  Didn't do any of the steps mentioned in the Realm Installation Document in their website.
It creates the Archieve, Validates but while trying to submit to iTunes I was getting errors as shown above in screenshots.

3) Next with the manual steps, tried to follow  all steps  mentioned in the Realm Installation Document in their website. I get error when Archieve is created.

I am stuck. Thanks for your help.

**Comment by JhimliBora** [comment]
Its working for me now. Tried all the steps in Realm Swift documentation. But this time I removed the Run script section in Build Phases and added a new one and pasted the code in step 4 of the documentation bash"${BUILT_PRODUCTS_DIR}/${...

The submitting to App store was causing Xcode to crash. I used appLoader to submit the new build.

**Comment by jpsim** [comment]
Glad you got this working by following the instructions in our docs :+1:
