### ISSUE TITLE
RLMAccessor.h and RLMArray_Private.hpp not found (RealmSwift)

### ISSUE THREAD

**Issue by malcommac** [realm/realm-cocoa#1879]
Hi guys, I've just downloaded via CocoaPods the last version of Realm, RealmSwift (pod 'RealmSwift').
In my pods targets I've both Realm and RealmSwift (is it normal?)

Btw when I try to compile my project this is the error:
```
.../Pods/Realm/Realm/RLMAccessor.mm:19:9: 'RLMAccessor.h' file not found
.../Pods/Realm/Realm/RLMArray.mm:19:9: 'RLMArray_Private.hpp' file not found
```

(I haven't tried to put RealmSwift framework manually into the project yet, this is the result with cocoapods. I've also tried to remove the old pod and install the new again, but the result is the same)

**Comment by segiddins** [comment]
Are you using CocoaPods 0.37.1?

**Comment by malcommac** [comment]
Yes:
Danieles-MBP daniele$ gem which cocoapods
/Users/daniele/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.37.1/lib/cocoapods.rb

Tried with an empty project:
/Users/daniele/Desktop/TestApp/Pods/Realm/Realm/RLMArray.mm:19:9: 'RLMArray_Private.hpp' file not found

**Comment by malcommac** [comment]
I've also uploaded the empty test project here if it can help:
https://dl.dropboxusercontent.com/u/103260/RealmSwiftTestAppCocoaPods.zip

**Comment by blodely** [comment]
Got same error in realm-objc. 
Couldn't find header files...
![screen shot 2015-05-09 at 11 32 49 am](https://cloud.githubusercontent.com/assets/1422985/7548512/2c7f7392-f63f-11e4-9f00-f83bb2ba4def.png)

**Comment by malcommac** [comment]
Any news?

**Comment by segiddins** [comment]
@malcommac I was able to resolve the issue with the sample project you provided by deleting the `Pods` dir and re-running `pod install` -- could you try that out and see if it resolves things?

**Comment by malcommac** [comment]
Well seems it was fixed in the meantime :-)

**Comment by flipchen** [comment]
The problem still persists, even after deleting the Pods directory and doing a clean install of all the dependencies.

**Comment by jpsim** [comment]
@flipchen what can we do to help? Please make sure you're using CocoaPods 0.37.1 and that you're starting from a fresh CocoaPods cache (`rm -rf ~/Library/Caches/CocoaPods`) and clear your existing Pods (`rm -rf Pods`) before attempting to run `pod update`.

**Comment by flipchen** [comment]
@jpsim I tried all that already and in the end simply rolled back to 0.92.2 to continue working on my app. I'll have another go when you guys release 0.92.4 or so. Maybe it all resolves by itself.

**Comment by flipchen** [comment]
And it did when I moved to 0.92.4. Strange, but I certainly won't complain!

**Comment by aniketayachit** [comment]
My pod file updated to 0.95.3, I got same problem of RLMArray_Private.hpp not found.

**Comment by jpsim** [comment]
@aniketayachit please file a bug with CocoaPods, as it's a caching issue on their end.
