### ISSUE TITLE
Realm crashes upon initialization

### ISSUE THREAD

**Issue by conradev** [realm/realm-cocoa#2182]
```
group.cpp:136: [realm-core-0.89.3] Assertion failed: size_t(m_top.get(2) / 2) <= m_alloc.get_baseline() [393216, 335872]
0   Realm                               0x0000000101dd2180 _ZN5realm4util18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 44
1   Realm                               0x0000000101d93f00 _ZN5realm4util9terminateImmEEvPKcS3_lT_T0_ + 396
2   Realm                               0x0000000101e4e5e0 _ZN5realm5Group13init_from_refEm + 620
3   Realm                               0x0000000101e5a87c _ZN5realm11SharedGroup10begin_readENS0_9VersionIDE + 188
4   Realm                               0x0000000101dbbaa0 -[RLMRealm getOrCreateGroup] + 64
5   Realm                               0x0000000101dc5720 RLMRealmSchemaVersion + 40
6   Realm                               0x0000000101d9ad2c RLMUpdateRealmToSchemaVersion + 100
7   Realm                               0x0000000101dbc3b0 +[RLMRealm realmWithPath:key:readOnly:inMemory:dynamic:schema:error:] + 1252
8   Realm                               0x0000000101dbbd30 +[RLMRealm realmWithPath:readOnly:error:] + 52
9   Realm                               0x0000000101dbbc98 +[RLMRealm defaultRealm] + 76
10  WorkflowUI                          0x0000000101c3ed28 -[WFWorkflowsViewController init] + 60
11  Workflow                            0x00000001000ea1b4 -[WFAppDelegate application:willFinishLaunchingWithOptions:] + 548
12  UIKit                               0x000000018a67b070 <redacted> + 224
13  UIKit                               0x000000018a8927e8 <redacted> + 2376
14  UIKit                               0x000000018a89519c <redacted> + 1504
15  UIKit                               0x000000018a89370c <redacted> + 184
16  FrontBoardServices                  0x000000018e3c53c8 <redacted> + 32
17  CoreFoundation                      0x0000000185b4827c <redacted> + 20
18  CoreFoundation                      0x0000000185b47384 <redacted> + 312
19  CoreFoundation                      0x0000000185b459a8 <redacted> + 1756
20  CoreFoundation                      0x0000000185a712d4 CFRunLoopRunSpecific + 396
21  UIKit                               0x000000018a6743d0 <redacted> + 552
22  UIKit                               0x000000018a66ef40 UIApplicationMain + 1488
23  Workflow                            0x00000001000e9f60 main + 124
24  libdyld.dylib                       0x0000000197f06a08 <redacted> + 4
IMPORTANT: if you see this error, please send this log to help@realm.io.
```

Also sent to help@realm.io

**Comment by segiddins** [comment]
Thanks for sending this over @conradev -- this was an issue with our usage of `ftruncate()` and `fsync()` that was fixed in the 0.93.2 release, which I strongly recommend updating to.

**Comment by conradev** [comment]
Awesome, thanks, will update!

**Comment by conradev** [comment]
@segiddins, I just updated to 0.93.2 and the app is still crashing. Do I need to delete the Realm file?

**Comment by segiddins** [comment]
@conradev yes. The Realm file has lost some data, but the conditions that allowed for such a file to be generated are now gone.
