### ISSUE TITLE
'Object' subclasses don't conform to Equatable protocol.

### ISSUE THREAD

**Issue by nostrouh** [realm/realm-cocoa#2519]
Xcode 7 GM, Swift 2.0. Using branch 'swift-2.0'.

When I started to migrate my project to swift 2.0, I have noticed that I unable to store 'Object' subclasses in collections that require it's elements to conform to Equatable protocol. And as result Hashable as well.

Here is the simplest example to reproduces it.
```swift
class A: Object {
}

let array = Set<A>()

let instance = A()
let index = [A]().indexOf(instance)
 ```

When you will try to compile that code you will get error on set initialization that type 'A' does not conform to protocol Hashable. And that there is no method 'indexOf' for supplied parameters (indexOf(element) requires element to conform to Equatable).

![image](https://cloud.githubusercontent.com/assets/592804/9814083/e05eead0-5893-11e5-986d-f0689ed0d720.png)

But on other case set of 'object' instances works fine.
```swift
let object = Set<Object>()
 ```

Could you help to find what can cause this issue?

**Comment by bdash** [comment]
I can reproduce this, but I'm not sure why it's happening. `Object` inherits conformance to `Equatable` and `Hashable` by virtue of being a subclass of `NSObject`. I'm not sure why that doesn't apply to subclasses of `Object`.

The following change to how `A` is declared appears to give the expected results:

``` swift
public class A: Object, Equatable, Hashable {
}

public func ==(lhs: A, rhs: A) -> Bool {
    return lhs.isEqual(rhs)
}
```

@jpsim, @tgoyne, do you have any idea why conformance to `Equatable` and `Hashable` have to be redeclared?

**Comment by jpsim** [comment]
I wonder if explicitly claiming `Hashable` on `Object` would work around this issue. In any case, this definitely sounds like a bug in Swift and a radar should be filed.

**Comment by jpsim** [comment]
> I wonder if explicitly claiming Hashable on Object would work around this issue.

Although this works in Swift 1.2, Swift 2.0 fails to compile with the error `redundant conformance of 'Object' to protocol 'Hashable'`. This can only really be fixed by Apple, as I can't really think of a workaround that wouldn't require avoiding inheriting from `NSObject`, which isn't feasible at the moment.

**Comment by jpsim** [comment]
Turns out that this bug only applies to Xcode 7.0, and that Xcode 6.4 and 7.1 are unaffected. I'm closing this issue since it's a bug in Swift itself, and resolved as of Xcode 7.1.

The workaround @bdash suggested above should be sufficient for those of you on Xcode 7.0.

**Comment by jpsim** [comment]
Looks like this was also fixed in Xcode 7.0.1, officially released today.

**Comment by suleymancalik** [comment]
Hi,
I am still facing this problem with 7.0.1 and 7.1 beta 3

**Comment by jpsim** [comment]
@suleymancalik could you please share a complete code sample that demonstrates the issue you're having? We haven't been able to reproduce this issue as of Xcode 7.0.1.

**Comment by suleymancalik** [comment]
@jpsim 

It happens while using Object's subclass as dictionary key. You can see my project's errors and structure.

I have also created a sample repo for issue.
https://github.com/suleymancalik/RealmTest



![ekran resmi 2015-10-21 10 04 18](https://cloud.githubusercontent.com/assets/445127/10629877/48ffde9e-77db-11e5-91d9-04c2ce9755d5.png)

![ekran resmi 2015-10-21 10 04 33](https://cloud.githubusercontent.com/assets/445127/10629885/54b1d864-77db-11e5-9f87-c245e691455c.png)

![ekran resmi 2015-10-21 10 04 44](https://cloud.githubusercontent.com/assets/445127/10629887/58db7896-77db-11e5-8024-a71cac86979c.png)

![ekran resmi 2015-10-21 10 04 54](https://cloud.githubusercontent.com/assets/445127/10629888/5c28e6fa-77db-11e5-9f5d-d3eeeb1c0fe6.png)

**Comment by jpsim** [comment]
Thanks for the sample project, @suleymancalik. I've confirmed that this is still an issue in Xcode 7.0.1 and Xcode 7.1 Beta 3.

I'm curious as to why it worked the last time I checked... maybe I tried with an OS X project?

In any case, I think the first thing to do here is to file a radar with Apple at bugreport.apple.com indicating this is a regression. Then we can look into ways that we could work around this from within Realm Swift itself.

Until then, you'll have to use the workaround described by @bdash above.

**Comment by ozgur** [comment]
Problem still occurs in Xcode 7.3 and Swift 2.2.

**Comment by jpsim** [comment]
@ozgur have you filed a radar or a ticket on bugs.swift.org? Those are probably the most effective ways of informing Apple about the problem.

**Comment by tannauit** [comment]
```
func ==(lhs: MGInboxMessage, rhs: MGInboxMessage) -> Bool {
    return false
}

final class MGInboxMessage: MGRealmObject, Equatable {
....
}
```

It works for me when I declared in in global scope

**Comment by SemperIdem** [comment]
My solution is:
`
extension RealmModel: Hashable { }

func ==(lhs: RealmModel, rhs: RealmModel) -> Bool {
  //...Do your judgement here
}
`
It works for me.

**Comment by ozgur** [comment]
This issue is not reproducible in Xcode 7.3.1. Probably they fixed this compile issue.

**Comment by harryworld** [comment]
I have the same issue.
@ozgur what's your solution to this?

**Comment by basvankuijck** [comment]
@harryworld: Removing the redundant `Equatable` statement and overriding the obj-c `isEqual:` function, did the trick for me. Can't say if this is a acceptable solution at all.

**Comment by jmejiaa** [comment]
@ozgur while the issue of Objects nor conforming seems to be fixed, any subclasses wanting to override the Equatable and Hashable methods seem to be ignored.

I'm Seeing the same issue here after upgrading from 7.3 to 7.3.1, sadly it looks like it's now ignoring my implementations of the Hashable and Equatable methods on my Object subclasses.

Overriding isEqual as suggested by @harryworld solves it on my end as well.

**Comment by jpsim** [comment]
This appears to be fixed in Swift 2.2, as confirmed by running this in the Swift REPL:

```
$ swift -F /Users/jp/Downloads/realm-swift-0.103.1/osx/swift-2.2
Welcome to Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.30). Type :help for assistance.
  1> import Foundation; import RealmSwift; dlopen("/Users/jp/Downloads/realm-swift-0.103.1/osx/swift-2.2/RealmSwift.framework/RealmSwift", 2) 
$R0: UnsafeMutablePointer<Void> = 0x0000000101500940 -> 0x00007fff5fc38e48 dyld`vtable for ImageLoaderMachOCompressed + 16
  2> class MyModel: Object { dynamic var prop = "" } 
  3> let set: Set = [MyModel()]
set: Set<MyModel> = {
  [0] = {
    RealmSwift.Object = {
      Realm.RLMObjectBase = {
        RLMObjectBase = {
          NSObject = {
            isa = RLMStandalone_MyModel
          }
          _realm = nil
          _objectSchema = {
            NSObject = {
              isa = RLMObjectSchema
            }
            _isSwiftClass = true
            _propertiesInDeclaredOrder = nil
            _swiftGenericProperties = nil
            _properties = 1 element
            _className =
            _primaryKeyProperty = nil
            _allPropertiesByName = 1 key/value pair
            _objectClass = __lldb_expr_3.MyModel
            _accessorClass = RLMDynamicObject
            _standaloneClass = RLMStandalone_MyModel
            _computedProperties = 0 elements
            _realm = nil
          }
        }
      }
    }
    prop = ""
  }
}
  4> :quit
```

**Comment by EstebanVallejo** [comment]
I've just updated from Xcode 7.3  to  Xcode  7.3.1 and I started getting this error too.
With Xcode 7.3 I had no troubles with this.

I'm using Realm 1.0.0 (latest in cocoapods)
"
...
Installing Realm (1.0.0)
Installing RealmSwift (1.0.0)
...
"

Attaching screen shot:
![user_swift](https://cloud.githubusercontent.com/assets/6104728/15652999/7e548b1a-2660-11e6-8bcb-4eceef5bad1d.png)

**Comment by mrackwitz** [comment]
@EstebanVallejo: The compiler error you're facing confirms that the underlying problem of this issue is now resolved. Please remove the redundant `Equatable` protocol conformance declaration and override instead the Objective-C `isEqual:` method on your `User` class, if you want to provide a different implementation than what Realm provides by default. Note that if your `id` property is a primary key, this is not at all necessary.

**Comment by frederic-adda** [comment]
This is not what I've seen. I have a subclass of Object, for which a property `id` is declared as the primaryKey. If I check if an array of this subclass contains an element before actually appending this element, the result of this check is wrong.

I have to manually check if the array contains an element with an id correpsonding to the id of the element I want to append. This is such a waste of time.

**Comment by jpsim** [comment]
@frederic-adda I'm not sure I fully understand everything from your last comment, but it sounds like you should be [filing a new issue](https://github.com/realm/realm-cocoa/issues/new), detailing exactly what you're doing, what you think should happen, what's actually happening instead and share code samples for us to reproduce.
