### ISSUE TITLE
objectsWithPredicate: causing EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by uson1x** [realm/realm-cocoa#3266]
Hey,

I'm trying to figure out what is causing EXC_BAD_ACCESS crashes, which we see in our Crashlytics reports. Does that look like something that was potentially fixed in any release after 0.96.2 (which is used in this build)?

## Actual Results
```
Thread : Crashed: com.apple.main-thread
0  edagsorden                     0x100263c64 long long realm::Array::get<4ul>(unsigned long) const + 8
1  edagsorden                     0x10033f5c0 realm::Table::get_link_chain_target(std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&) const + 53220
2  edagsorden                     0x1001fa42c void (anonymous namespace)::add_constraint_to_query<unsigned long, objc_object* __strong>(realm::Query&, RLMPropertyType, NSPredicateOperatorType, unsigned long, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&, unsigned long, objc_object* __strong) (array.hpp:1983)
3  edagsorden                     0x1001f5298 (anonymous namespace)::update_query_with_value_expression(RLMSchema*, RLMObjectSchema*, realm::Query&, NSString*, objc_object*, NSComparisonPredicate*) (RLMQueryUtil.mm:906)
4  edagsorden                     0x1001f2680 (anonymous namespace)::update_query_with_predicate(NSPredicate*, RLMSchema*, RLMObjectSchema*, realm::Query&) (RLMQueryUtil.mm:1016)
5  edagsorden                     0x1001f2884 (anonymous namespace)::update_query_with_predicate(NSPredicate*, RLMSchema*, RLMObjectSchema*, realm::Query&) (RLMQueryUtil.mm:965)
6  edagsorden                     0x1001f2214 RLMUpdateQueryWithPredicate(realm::Query*, NSPredicate*, RLMSchema*, RLMObjectSchema*) (RLMQueryUtil.mm:1076)
7  edagsorden                     0x1001e478c RLMGetObjects (RLMObjectStore.mm:581)
8  edagsorden                     0x1001daa0c +[RLMObject objectsWithPredicate:] (RLMObject.mm:127)
9  edagsorden                     0x10010d6bc +[RealmStorageManager kommentarSporForSync] (RealmStorageManager.m:116)
...
```

OR

```
Thread : Crashed: com.apple.main-thread
0  edagsorden                     0x10018e844 long long realm::Array::get<4ul>(unsigned long) const + 8
1  edagsorden                     0x10014d0b8 realm::LinkMap::init(realm::Table*, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >) (vector:1501)
2  edagsorden                     0x10014cfd8 realm::Columns<bool>::Columns(unsigned long, realm::Table const*, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >) (query_expression.hpp:1340)
3  edagsorden                     0x10014b4c4 void (anonymous namespace)::add_constraint_to_query<unsigned long, objc_object* __strong>(realm::Query&, RLMPropertyType, NSPredicateOperatorType, unsigned long, std::__1::vector<unsigned long, std::__1::allocator<unsigned long> >, unsigned long, objc_object* __strong) (query_expression.hpp:1339)
4  edagsorden                     0x100148dd4 (anonymous namespace)::update_query_with_value_expression(RLMSchema*, RLMObjectSchema*, realm::Query&, NSString*, objc_object*, NSComparisonPredicate*) (RLMQueryUtil.mm:611)
5  edagsorden                     0x1001447f8 (anonymous namespace)::update_query_with_predicate(NSPredicate*, RLMSchema*, RLMObjectSchema*, realm::Query&) (RLMQueryUtil.mm:793)
6  edagsorden                     0x1001449e4 (anonymous namespace)::update_query_with_predicate(NSPredicate*, RLMSchema*, RLMObjectSchema*, realm::Query&) (RLMQueryUtil.mm:742)
7  edagsorden                     0x10014439c RLMUpdateQueryWithPredicate(realm::Query*, NSPredicate*, RLMSchema*, RLMObjectSchema*) (RLMQueryUtil.mm:853)
8  edagsorden                     0x100142224 RLMGetObjects (RLMObjectStore.mm:710)
9  edagsorden                     0x100138c88 +[RLMObject objectsWithPredicate:] (RLMObject.mm:133)
10 edagsorden                     0x100079448 +[RealmStorageManager kommentarSporForSync] (RealmStorageManager.m:116)
...
```

## Steps to Reproduce

Unfortunately I was not able to reproduce this on my device yet.

## Code Sample

The line which is causing this:

```
RLMResults *result = [OfflineKommentarSpor objectsWithPredicate:[NSPredicate predicateWithFormat:@"ANY kommentarer.newComment == 1 OR deleted == 1 OR modified == 1"]];
```

It seems to be working fine most of the time, but we see occasional crash reports

## Version of Realm and Tooling

As Crashlytics points out, this is happening on iPad 2 - iPad Air 2, iOS 8.1.1 - iOS 9.2.1.

```
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21

/Applications/Xcode.app/Contents/Developer
Xcode 7.2.1
Build version 7C1002

/Users/username/.rvm/gems/ruby-2.0.0-p643/bin/pod
0.39.0
Realm (0.96.2)
Realm (~> 0.96.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/bin/git
git version 2.5.4 (Apple Git-61)
```

Any hint would be really appreciated. Thank you!

**Comment by jpsim** [comment]
Hi @uson1x, are there stack frames from other threads terminating with an assertion or uncaught exception? The ones you've shared do not, which would suggest that some other thread is causing this crash.

@tgoyne is it possible that this query isn't being properly handed over? The form `ANY link.property OR property OR property` might provide some hints as to what may not be fully handover-supported.

**Comment by tgoyne** [comment]
The crash is in building the Query from the NSPredicate, so it's long before any handover would occur. Both of the crashes are in converting the keypath to a link chain, so /ping @bdash

**Comment by bdash** [comment]
I've not seen any reports of a crash like this before. The crash happens below a call to `Table::column` when retrieving a column to use in a query expression. Due to inlining it's hard to tell which objects are involved at the time of the crash. I think we'd need to find a reproducible case to be able to investigate this.

It's possible that this is an issue that's been fixed since v0.96.2. v0.96.2 was released back in October, and we've made many changes in query code since then.

**Comment by jpsim** [comment]
> v0.96.2 was released back in October, and we've made many changes in query code since then.

Oops, 0.96.2 is the current version of core, so I got a bit confused.

@uson1x please try again with the latest version of Realm (0.98.2) and report back to see if this is still an issue.

**Comment by jpsim** [comment]
@uson1x we're closing this ticket because we expect this issue to have been addressed in recent versions of Realm and haven't heard back from you in a few weeks. Please open a new issue if this happens with the latest version of Realm.

**Comment by uson1x** [comment]
Hi everyone,

Unfortunately upgrading to Realm 0.100.0 didn't fix this particular issue, there is a fresh crash report in Fabric with the following stack trace:

```
#0
Crashed: com.apple.main-thread
EXC_BAD_ACCESS 0x00000001066c16ff

0  edagsorden                     0x10026d780 long long realm::Array::get<4ul>(unsigned long) const + 8
1  edagsorden                     0x10035b734 realm::Table::get_link_chain_target(std::__1::vector<unsigned long, std::__1::allocator<unsigned long> > const&) const + 56600
2  edagsorden                     0x1001ecccc auto (anonymous namespace)::value_of_type_for_query<bool>(realm::Query&, (anonymous namespace)::ColumnReference const&) (array.hpp:2235)
3  edagsorden                     0x1001ed8f8 void (anonymous namespace)::add_constraint_to_query<(anonymous namespace)::ColumnReference, objc_object* __strong>(realm::Query&, RLMPropertyType, NSPredicateOperatorType, unsigned long, (anonymous namespace)::ColumnReference, objc_object* __strong) (RLMQueryUtil.mm:685)
4  edagsorden                     0x1001d56a8 (anonymous namespace)::update_query_with_value_expression(RLMSchema*, RLMObjectSchema*, realm::Query&, NSString*, objc_object*, NSComparisonPredicate*) (RLMQueryUtil.mm:991)
5  edagsorden                     0x1001d34fc (anonymous namespace)::update_query_with_predicate(NSPredicate*, RLMSchema*, RLMObjectSchema*, realm::Query&) (RLMQueryUtil.mm:1197)
6  edagsorden                     0x1001d2d9c (anonymous namespace)::update_query_with_predicate(NSPredicate*, RLMSchema*, RLMObjectSchema*, realm::Query&) (RLMQueryUtil.mm:1132)
7  edagsorden                     0x1001d2b24 RLMUpdateQueryWithPredicate(realm::Query*, NSPredicate*, RLMSchema*, RLMObjectSchema*) (RLMQueryUtil.mm:1264)
8  edagsorden                     0x1001c9fa8 RLMGetObjects (RLMObjectStore.mm:480)
9  edagsorden                     0x1001c066c +[RLMObject objectsWithPredicate:] (RLMObject.mm:150)
10 edagsorden                     0x1000c9b50 +[RealmStorageManager kommentarSporForSync] (RealmStorageManager.m:118)
```

There is also this Realm notification listener thread stack frame
```
RLMRealm notification listener
0  libsystem_kernel.dylib         0x183681528 kevent + 8
1  edagsorden                     0x10018f960 realm::_impl::ExternalCommitHelper::listen() (external_commit_helper.cpp:199)
2  edagsorden                     0x10018fb5c std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() (future:2331)
3  edagsorden                     0x10018fae4 std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() (future:1025)
4  edagsorden                     0x10018fcac std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) (memory:2516)
5  libsystem_pthread.dylib        0x183763b28 _pthread_body + 156
6  libsystem_pthread.dylib        0x183763a8c _pthread_body + 154
7  libsystem_pthread.dylib        0x183761028 thread_start + 4
```

And nothing else interesting.

This one happened on iPad Air device with iOS 9.3.1 (13E238) in our new build with Realm 0.100.0.
One detail I haven't mentioned is that this code is being executed in a response to a reachability state change (to online). I don't see any connection, but just wanted to mention this.

Does anyone have any ideas on what might be wrong here?
Thanks in advance.
