### ISSUE TITLE
[Swift 2.5.1] Realm DB size grows to over 1 GB and causing app crash

### ISSUE THREAD

**Issue by shuhaodo** [realm/realm-cocoa#4837]
## Goals

DB file stays at a reasonable level

## Expected Results

DB file size is at 10MB

## Actual Results

DB file size is at 1.88 GB and causes app crash

## Steps to Reproduce

I have got some additional info:

1. It still happened in v2.5.1
2. It happened to tens of thousands of users, causing a significant drop of DAU, and we can reproduce it easily too.
3. The app uses realm in multiple threads on the main thread and background threads through GCD. We don't use NSOperationQueue.
4. Write happens both on main thread and bg thread, but mainly on bg thread (>98% of the writes)
5. Read happens on both main and bg threads too, about 40% & 60%, it's hard to put an accurate number as we do not limit read access to certain threads.
6. We have app extensions so realm file is in shared group. But the extensions are rarely used.
7. Write to realm very frequently. We are an email app, lots of I/O happen when app comes to foreground.
8. Yes, multiple threads are writing simultaneously.

The latest instance happened this morning. When I checked the DB size last night, it was 10MB; This morning it was 1.88GB when it's opened. As an email app, it would fetch email in the background mode when push notifications came in. There were about 5 notifications came in last night.

## Code Sample

No code sample was provided.

## Version of Realm and Tooling

- Realm framework version: 2.5.1
- Xcode version: 8.3
- iOS/OSX version: 10.3

**Comment by istx25** [comment]
Hi @shuhaodo. Thanks for filing this separate issue. We'll review what you've shared and someone will follow-up with you where necessary.

**Comment by shuhaodo** [comment]
The latest instance happened this morning. When I checked the DB size last night, it was 10MB; This morning it was 1.88GB when it's opened. As an email app, it would fetch email data in the background mode when a push notification comes in. There were about 5 notifications last night.

**Comment by tgoyne** [comment]
Are you performing a very large number of very small write transactions when handling each notification? It should not be possible to get a 200x magnification of the live data size from just five write transactions even in the problematic cases.

**Comment by shuhaodo** [comment]
We put most of the writes in a group. But there could be 10 to 20 small transactions in each app session.

The heaviest write transactions happen when there are lots of new emails to fetch and store. But it seems the problem is not related to the load of the write transactions. For example, we have a script to login 15 emails accounts and pull and store emails simultaneously, unto 10,000 concurrently in a short time period. And DB size stays under 10MB.

However, the issue can happen randomly at any time opening the app again, there could be no new email to store or update at all, only a few write transactions to update app level states. But the DB is exploded to GB level. Actually, when the issue happened, most of the time the app isn't doing much.

Hope this helps!

**Comment by bdash** [comment]
@shuhaodo, would it be possible for you to share a built IPA of your app with us along with steps to reproduce the problem? That'd allow us to install the app on an iOS device, reproduce the problem, and debug what's happening.

A few more questions:

1. Are you using Realm Objective-C or Swift?
2. Can you share a code snippet demonstrating how you're performing your writes on a background dispatch queue?

**Comment by shuhaodo** [comment]
Sure. We are using Swift. I can add you to Test Flight. Which email address should I use?

**Comment by bdash** [comment]
Would it be possible to share a built IPA with us instead of going via TestFlight? Sharing an IPA would allow me to replace the Realm frameworks within your app with those that have custom logging added to help understand the problem. I don't think that would be possible if TestFlight is in the middle. If this would work for you, please share the IPA with help@realm.io and include a link to this GitHub issue in your email.

**Comment by shuhaodo** [comment]
Got you. Will do it later today. Thanks!

**Comment by bdash** [comment]
You shouldn't need my UDID, no. I'll be re-signing the built app using my Apple developer identity to allow it to be installed on my device, which will also allow me to re-sign it after I drop in Realm frameworks with more logging as I investigate the problem.

**Comment by bdash** [comment]
One other question that just came to mind: have you verified that all of your Realm-related operations on background dispatch queues are wrapped in autorelease pools?

**Comment by shuhaodo** [comment]
Most of them are in autorelease pools, not all. I will share the db code shortly.

**Comment by bdash** [comment]
Ok. Any Realm-related work on a dispatch queue that's not inside an explicit autorelease pool has the potential to cause file size growth. The reason for this is that each Realm accessor object (`Realm`, `Object` instances, `Results`, `List`, etc.) has a reference to a specific version of the data within the Realm file. That version of data within the Realm file can only be reclaimed and reused once all accessor objects that refer to it have been deallocated. If these objects are not allocated within explicit autorelease pools when on a dispatch queue, they will escape into the _queues_ autorelease pool. GCD only drains the queue-level autorelease pools relatively infrequently, which can result in the lifetimes of these objects (and thus of the older versions of data in the Realm file) being significantly longer than you expect. I'd suggest auditing your code to ensure that all Realm-related work on dispatch queues happens within explicit autorelease pools.

**Comment by shuhaodo** [comment]
Yes, we are aware of that. The issue is really the sudden increase of the DB size (10MB -> 1.x G) at a random pattern. I would expect the DB size slowly builds up.

**Comment by bdash** [comment]
If the accessor objects happen to live much longer than anticipated then that could cause every write transaction until they're deallocated to grow the file. The scale of the growth is certainly surprising and may indicate some other factor is at play, but it's best to rule out the simple things first.

**Comment by hyouuu** [comment]
Out of curiosity, @shuhaodo I guess the app existed before Realm 2.2 came out, and it hasn't been an issue before? It would help @bdash to scope the issue too I think.

**Comment by hyouuu** [comment]
Also related is in my case (https://github.com/realm/realm-cocoa/issues/4832), I'm solely using Realm on the main thread but still got the sizing issue

**Comment by bdash** [comment]
@hyouuu, please keep discussion of your scenario to the issue you filed. Spreading it across multiple issues just confuses the matter.

**Comment by shuhaodo** [comment]
I have sent the ipa and code snippet to help@realm.io. Let me know if anything else I could provide!

**Comment by bdash** [comment]
Thanks for sending that over, @shuhaodo. Sadly I've been unable to convince it to run on my iPhone (I've been unable to convince iOS to accept a provisioning profile that works with the various different entitlements your app requires).

I'd suggest that the next steps here should be to audit your codebase for missing autorelease pools as I described earlier. Once you have addressed those problems you should then test whether you can still reproduce the file size growth.

**Comment by shuhaodo** [comment]
Will do and post updates here.

**Comment by shuhaodo** [comment]
more questions:
1. Is it necessary to call realm.invalidate() - we don't use this at all
2. Before every read or write, realm.refresh() is called. Will that be an issue? We didn't notice any performance issue. Without calling realm.refresh(), sometimes the realm instance on main thread is not up to date and causing data inconsistency.

**Comment by bdash** [comment]
[`Realm.invalidate()`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm10invalidateFT_T_) detaches all accessor objects associated with the Realm and closes the read transaction it has open, releasing the reference to the version of data that it was looking at within the Realm file. This is basically equivalent to what happens when the `Realm` instance is deallocated. `invalidate()` just allows you to force it to happen prior to the `Realm` being deallocated, with the tradeoff being that any access to accessor objects will throw (except for checking whether they're invalidated).

The Realm on the main thread should be [automatically refreshing](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:vC10RealmSwift5Realm11autorefreshSb) itself to the latest version on each runloop iteration. When are you seeing it be not up to date? If it's when `dispatch_aysnc`ing to the main thread immediately after a write transaction it's possible for the async block to be dequeued and invoked before Realm's commit notification makes it to the main thread. In this case you may see the Realm as not having refreshed to the latest version, and calling `Realm.refresh()` is the correct way to deal with that.

**Comment by shuhaodo** [comment]
Thanks @bdash, yes, occasionally when dispatch_async to main thread. So calling realm.refresh() every time won't cause stability issue right?

Now all the GCD queues will run in autorelease pool:

`dbQueue = dispatch_queue_create("com.edo.DB.bg.queue", dispatch_queue_attr_make_with_qos_class(DISPATCH_QUEUE_CONCURRENT_WITH_AUTORELEASE_POOL, QOS_CLASS_USER_INTERACTIVE, 0));`

**Comment by bdash** [comment]
> So calling realm.refresh() every time won't cause stability issue right?

No. The only thing to be aware of is that calling `refresh()` will trigger any collection / object notifications that need to be fired when advancing from the old version of the Realm to the latest version.

> Now all the GCD queues will run in autorelease pool

Very cool. I'll keep `DISPATCH_QUEUE_CONCURRENT_WITH_AUTORELEASE_POOL` in mind when talking to users in the future. It does mean you'll need to be very sure you're not reading or writing your Realm on any other dispatch queue (or that those will also need similar autorelease pool handling). This sometimes comes up when doing work in response to callbacks from your networking stack, or other asynchronous work, where the callback runs on an arbitrary background queue.

**Comment by shuhaodo** [comment]
We streamlined all the background executions to the dedicated queues, including network callbacks, so this should catch 'em all.

On the refresh() note, we don't use notification block or observation,  and main thread does not have persisted realm objects (they are converted to pain objects for simplicity and thread safe). With that said, is it correct to say refresh() wouldn't impact the performance? I don't notice performance difference with or without calling refresh().

**Comment by bdash** [comment]
There shouldn't be a performance impact, no. Calling `refresh()` explicitly on the main thread just performs work that would otherwise happen on a subsequent runloop iteration, when our auto refresh mechanism does its work.

**Comment by jpsim** [comment]
First, let me reiterate that large Realm files are likely due to holding old versions of data in a background thread for extended periods of time. Realms opened on threads without a runloop don't auto-refresh, so you'll need to take special care to wrap background Realm access in self-contained `@autoreleasepool` blocks that don't leak any Realm-related types.

However, we understand that debugging these cases can be difficult, and even if you don't leak Realms, file sizes can be larger than you'd expect.

So I'd like to encourage everyone who's experienced large Realm file sizes to try out the new `shouldCompactOnLaunch` block on `Realm.Configuration`, available as of today's 2.6 release: https://realm.io/docs/swift/latest/#compacting-realms

I wanted to provide a default implementation so this would be on-by-default, but struggled to find good one-size-fits-all heuristics. I think some form of "compact on launch" should be Realm's default mode of operation. So I look forward to hearing what settings people end up using in practice and what ends up working best. Please share feedback from this so we can confidently enable something like this for everyone out of the box.

**Comment by kashifshaikh** [comment]
GCD and OperationQueues are a common staple of iOS programs, the documentation needs to be made clear that autoreleasepools *MUST* be used as @bdash stated above. You have one sentence in a long paragraph "....To avoid this issue, you should use an explicit autorelease pool when accessing a Realm from a dispatch queue." You're like beating around the bush around GCD usage.

Make THIS BOLD and under a different header - so every developer understands the requirements. ALMOST all programs will always access Realm from a background thread - NSURLSession callbacks for instance always execute on a background thread, so it's very common that Realm writes will be be done from the same thread.

**Comment by jpsim** [comment]
Hi @kashifshaikh thanks for the suggestion. I agree that we need to bring more attention to the situation. I'll be making some changes to the relevant docs sections and will let you know when that should be live.

We're also working on adding some convenience APIs for working with Realm's thread-safe references which should apply these best practices automatically to minimize the need for Realm developers to carefully consider these implications every time they access Realms on threads with no autoreleasepools or runloops.

**Comment by TimOliver** [comment]
In case it's not visible publicly, we've updated our documentation highlighting the pitfalls of version pinning if you don't use `autoreleasepool` blocks.

It looks like all the questions in this issue have been answered. I'm going to close it off, but feel free to re-open if there's anything outstanding. :)

**Comment by 0v3rst33r** [comment]
I know this is closed already, but @shuhaodo did you manage to solve your problem in the end?  I couldn't find where you explicitly states that your issue has been resolved.

**Comment by shuhaodo** [comment]
It still happens but less frequently after using autoreleasepool.

**Comment by 0v3rst33r** [comment]
@shuhaodo we have been having similar issues until last week.  We are also using lots of queues, etc.  Our Realm file grew within 30 mins to 1.8GB, and then app crash occurs.

I found that using `autoreleasepool` only does not do the trick.  `Realm.invalidate()` to the rescue.

Pseudo code snippet from *all* our access to the Realm data store:

```
let realm = try! Realm()
defer { realm.invalidate() }
// code that access the above realm instance
```
We obviously NEVER return from our data access class any `attached` Realm objects, because you will get an exception accessing these objects after calling `invalidate()`.

We have great success with this pattern, ran the app for a few days now, and we have a million records in Realm and the datasize is < 200MB still.

Hope this info might help you.

**Comment by steelzeh** [comment]
Why is this closed? Shit still doesn't work, my file size increased to 12GB!!!
I am running on main thread, and using autoreleasepools.

I am converting 2kb of json to models, which are then added to realm, and each time it does that, the file size increases around 30mb, 40mb, 50mb, and after a while 100mb each time?

I convert the realm database models to my API Models, since i cant use realm database models, because if data changes they become invalidated?

I have read through this thread, and nothing helps. How can i fix this? I'd rather lose some realm performance instead of having 12gb realm files after 2 days after loading in 2kb of data....

**Comment by harishthanniruios** [comment]
Hi I  m using realm in my project but I m facing a problem that first it  is saving record Id and after sometime it is showing that there is no record Id can anyone help me
