### ISSUE TITLE
RealmConfiguartion.swift compile error: Generic parameter 'U' could not be inferred

### ISSUE THREAD

**Issue by oyalhi** [realm/realm-cocoa#5124]
## Goals

Compile an empty project with only RealmSwift using cocoapods.

## Expected Results

Successful compile of an empty single view iOS app with RealmSwift.

## Actual Results

Realm 2.8.3 was working fine with Xcode 9 Beta 2, after upgrading to Xcode Version 9.0 beta 3 (9M174d) the RealmConfiguration.swift file gives error, on line 226.

the line is:
`configuration.shouldCompactOnLaunch = self.shouldCompactOnLaunch.map(ObjectiveCSupport.convert)`

The error is:
`Generic parameter 'U' could not be inferred`

## Steps to Reproduce

Create a single view application for iOS using Xcode. Add RealmSwift 2.8.3 pod to your project. Try compiling. It fails.

## Version of Realm and Tooling

Realm framework version: 2.8.3

Realm Object Server version: not used

Xcode version: Xcode 9 Beta 3 (9M174d)

iOS/OSX version: iOS 10 & 11

Dependency manager + version: /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods.rb

**Comment by jpsim** [comment]
This was fixed in #5109.

**Comment by oyalhi** [comment]
I am using RealmSwift via cocoapods, and pod update does not resolve the issue for me. I still get the error. When should we expect a pod update please?

**Comment by jpsim** [comment]
You don't need an official release to build Realm Swift from source on a branch, just specify the following in your Podfile:

```ruby
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
```
