### ISSUE TITLE
Incorrect Filter results with IN

### ISSUE THREAD

**Issue by Vitalik13** [realm/realm-cocoa#6154]
## Goals
Correct filtering with predicate

## Expected Results
Return all objects with id which are in sequence.

## Actual Results
Return only some objects with id which are in sequence.
<img width="1044" alt="Снимок экрана 2019-05-27 в 21 18 38" src="https://user-images.githubusercontent.com/17448005/58434569-0312ff00-80c5-11e9-9057-daa0fd414d2a.png">

<img width="984" alt="Снимок экрана 2019-05-27 в 21 18 15" src="https://user-images.githubusercontent.com/17448005/58434573-0a3a0d00-80c5-11e9-81c1-8f9be49a4268.png">

## Steps to Reproduce
Call method 
var result = championship.events.filter("id IN %@",eventIds)

## Code Sample

     func filteredChampionshipResult() -> Results<Championship> {
        var result = current.objects(Championship.self)
        result = result.filter("SUBQUERY(events, $event, $event.id IN %@).@count > 0",eventIds)
        return result
    }
    
    func eventsResult(for championship:Championship) -> Results<Event> {
        var result = championship.events.filter("id IN %@",eventIds)
        return result
    }

## Version of Realm and Tooling
Realm framework version: 3.15.0

Xcode version: 10.2.1 (10E1001)

iOS/OSX version: 12.3.1

**Comment by tgoyne** [comment]
Assuming `id` doesn't have an index this'll hit the optimization added in https://github.com/realm/realm-core/pull/3271, which would point at a bug in that. If `id` does have an index (or is the primary key) then nothing should have changed about this in quite a while.

If you can privately share the app code and relevant data needed to reproduce this it'd probably be quite easy to figure out where things are going wrong, but otherwise it may be hard to figure out what the problematic case is as we do have some tests of IN on ints in a subquery.

**Comment by gshahbazian** [comment]
@tgoyne hi, thanks for pointing to that change. We were also seeing this bug with realm v3.16, and downgrading to release v3.14 (which doesn't include realm/realm-core#3271) fixes it for us.

Anything I can do to help reproduce/fix please let me know!

**Comment by tgoyne** [comment]
[Another user supplied a repro case for what's probably the same bug in realm-java](https://github.com/realm/realm-java/issues/6522#issuecomment-504447661) so we hopefully have what we need to fix this.

**Comment by tgoyne** [comment]
https://github.com/realm/realm-core/pull/3320 should fix this.

**Comment by gshahbazian** [comment]
@tgoyne after upgrading to 3.17.3 we still see the original issue. Was the bug in realm-java confirmed to be fixed?
