### ISSUE TITLE
xcodebuild timed out while trying to read SwiftPackageManagerExample.xcodeproj

### ISSUE THREAD

**Issue by cuongtv51** [realm/realm-cocoa#6549]
I try to integrate realm-cocoa by using Carthage

Each time i run `carthage update` it will output error
`xcodebuild timed out while trying to read SwiftPackageManagerExample.xcodeproj`
for Realm version 5.0.2

My Xcode is 10.15
Mac 10.15.5

**Comment by Sc4pego4t** [comment]
same
Mac 10.15.3
Xcode Version 11.3.1

**Comment by Sc4pego4t** [comment]
The root of the problem seems to be Swift Project Manager and my slow internet connection, it seems SPM dependencies have not enough time to download...
Fixed by opening checkouted project, and waiting for successful dependency downloading.
After that `carthage build realm-cocoa --no-use-binaries --platform iOS ` works fine

**Comment by cuongtv51** [comment]
5.0.3 is newest. Still have problem!
You can use `Network Link Conditioner` tool on Mac to limit network speed and this problem occur.
I think it my network is slow, but why when carthage build, why need buid `SwiftPackageManagerExample.xcodeproj` this?


Yes, @Sc4pego4t 's suggestion resolve problem.
Only 5.0.0 is OK!

**Comment by tgoyne** [comment]
We've seen this happen on our CI setup as well. The problem comes down to that calling `xcodebuild -list` on a xcode project which uses SPM downloads that project's dependencies, which combines very poorly with the fact that Carthage doesn't give a repo any control over where it looks for xcode projects and instead checks every single one of them.

**Comment by gbreen12** [comment]
I've been having the same issue using multiple different versions of Xcode, most recently 11.5.

**Comment by viktor-malieichyk** [comment]
Also encountered this issue during Carthage update

But it raises question: why this SwiftPackageManagerExample.xcodeproj have to be built in the first place?

**Comment by tgoyne** [comment]
It doesn't have to be built. Carthage just doesn't provide any way for us to tell it that.

**Comment by cuongtv51** [comment]
This issue prevent other want to use lib with carthage. Can we move example prj to other or any thing else?

**Comment by caobug** [comment]
I have this same issues, how to fix it?
```
carthage update realm-cocoa --platform iOS --cache-builds --no-use-binaries
```
```
*** Checking out realm-cocoa at "v5.2.0"
*** xcodebuild output can be found in /var/folders/hy/7syk08mn7cjc92jfsjl8vh2r0000gn/T/carthage-xcodebuild.eBNDSe.log
*** Invalid cache found for realm-cocoa, rebuilding with all downstream dependencies
```
```
xcodebuild timed out while trying to read SwiftPackageManagerExample.xcodeproj 😭
```

**Comment by marinofaggiana** [comment]
V 5.3.2 same issue ( yet )

**Comment by destryteeter** [comment]
Found this issue is reproducing with the latest dev environment:
- Xcode 12.3 (12C33)
- macOS Big Sur 11.1
```
*** Downloading realm-cocoa.framework binary at "v10.5.0"
***  Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8) and the local version is 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)."

    Falling back to building from the source
xcodebuild timed out while trying to read SwiftPackageManagerExample.xcodeproj 😭
```

I was able to circumvent the issue by manually deleting the example project after Carthage finished checking out and before Carthage attempted to build the dependency.

I will be transitioning to XCFrameworks soon, but for now I am faced with this issue still.
