### ISSUE TITLE
Opening realm fails on physical Apple TV 4K running tvOS 14

### ISSUE THREAD

**Issue by AndrewBarba** [realm/realm-cocoa#6790]
## Goals

Open Realm on Apple TV 4K running tvOS 14

## Expected Results

Realm opens successfully when running on physical Apple TV 4K on tvOS 14

## Actual Results

Crashes when running on physical device:

<img width="1536" alt="Screen Shot 2020-09-20 at 11 39 54 AM" src="https://user-images.githubusercontent.com/1316152/93715215-0b9f0c80-fb36-11ea-97ab-605f44bdc78b.png">

## Steps for others to Reproduce

Open any realm on tvOS 14 on a physical device. Note: it does not crash when running in a simulator.

Sample project using SPM: [RealmCrash.zip](https://github.com/realm/realm-cocoa/files/5252988/RealmCrash.zip)

## Version of Realm and Tooling

Realm framework version: 5.4.2

Xcode version: 12

tvOS version: 14

Dependency manager + version: CocoaPods v1.10

**Comment by jsflax** [comment]
Hey, I'll give this a try on my Apple TV and see if I can reproduce. Would you mind just sending on a small code sample for me to run?

**Comment by AndrewBarba** [comment]
@jsflax Here ya go, as simple as it gets.

[RealmCrash.zip](https://github.com/realm/realm-cocoa/files/5252988/RealmCrash.zip)

And here's a crash report I'm getting on this project (again only on physical device):

```
/Users/andrewbarba/Library/Developer/Xcode/DerivedData/RealmCrash-gnivnywwxrjnahdiuqxautfmueui/SourcePackages/checkouts/realm-core/src/realm/util/file.cpp:1040: [realm-core-6.0.26] Assertion failed: err == EEXIST with (err) =  [1]
0   RealmCrash                          0x00000001011135c8 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 28
1   RealmCrash                          0x0000000101113990 _ZN5realm4util19terminate_with_infoEPKcS2_lS2_OSt16initializer_listINS0_9PrintableEE + 316
2   RealmCrash                          0x0000000100a60a7c _ZN5realm4util19terminate_with_infoIJRiEEEvPKciS4_S4_DpOT_ + 132
3   RealmCrash                          0x00000001010d6b90 _ZN5realm4util4File4lockEbb + 856
4   RealmCrash                          0x0000000100e30c9c _ZN5realm4util4File18try_lock_exclusiveEv + 40
5   RealmCrash                          0x0000000100e2ece4 _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 1084
6   RealmCrash                          0x0000000100e322ec _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 288
7   RealmCrash                          0x0000000100e38450 _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 176
8   RealmCrash                          0x00000001009dc5d8 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 916
9   RealmCrash                          0x00000001009db7bc _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 68
10  RealmCrash                          0x00000001009db5d8 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 668
11  RealmCrash                          0x0000000100acc200 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 176
12  RealmCrash                          0x0000000100c07fd8 +[RLMRealm realmWithConfiguration:queue:error:] + 1796
13  RealmCrash                          0x0000000100c3a3a8 $sSo8RLMRealmC13configuration5queueABSo0A13ConfigurationC_So012OS_dispatch_C0CSgtKcfCTO + 156
14  RealmCrash                          0x0000000100c6cedc $s10RealmSwift0A0V5queueACSo012OS_dispatch_C0CSg_tKcfC + 152
15  RealmCrash                          0x000000010098a1b0 $s10RealmCrash11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0k6LaunchJ3KeyaypGSgtF + 112
16  RealmCrash                          0x000000010098a6d8 $s10RealmCrash11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0k6LaunchJ3KeyaypGSgtFTo + 212
17  UIKitCore                           0x00000001c705a2e8 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 10355432
18  UIKitCore                           0x00000001c705c1b4 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 10363316
19  UIKitCore                           0x00000001c7061830 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 10385456
20  UIKitCore                           0x00000001c685fa70 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 1989232
21  UIKitCore                           0x00000001c6ce0ed4 _UIScenePerformActionsWithLifecycleActionMask + 100
22  UIKitCore                           0x00000001c686057c 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 1992060
23  UIKitCore                           0x00000001c685ffac 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 1990572
24  UIKitCore                           0x00000001c6860390 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 1991568
25  UIKitCore                           0x00000001c685fc40 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 1989696
26  UIKitCore                           0x00000001c6867dc8 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 2022856
27  UIKitCore                           0x00000001c6c05264 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 5812836
28  UIKitCore                           0x00000001c6cf8700 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 244
29  UIKitCore                           0x00000001c6867b60 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 2022240
30  UIKitCore                           0x00000001c66beb3c 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 281404
31  UIKitCore                           0x00000001c66bd5dc 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 275932
32  UIKitCore                           0x00000001c66be788 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 280456
33  UIKitCore                           0x00000001c705fa0c 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 10377740
34  UIKitCore                           0x00000001c6c26db8 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 5950904
35  FrontBoardServices                  0x000000019f773728 078DB715-B364-3FF9-8837-4CDD75BCB013 + 46888
36  FrontBoardServices                  0x000000019f79b038 078DB715-B364-3FF9-8837-4CDD75BCB013 + 208952
37  FrontBoardServices                  0x000000019f780e84 078DB715-B364-3FF9-8837-4CDD75BCB013 + 102020
38  FrontBoardServices                  0x000000019f79ad4c 078DB715-B364-3FF9-8837-4CDD75BCB013 + 208204
39  libdispatch.dylib                   0x00000001024965fc _dispatch_client_callout + 16
40  libdispatch.dylib                   0x0000000102499ac4 _dispatch_block_invoke_direct + 232
41  FrontBoardServices                  0x000000019f7bf9e4 078DB715-B364-3FF9-8837-4CDD75BCB013 + 358884
42  FrontBoardServices                  0x000000019f7bf6ac 078DB715-B364-3FF9-8837-4CDD75BCB013 + 358060
43  FrontBoardServices                  0x000000019f7bfb80 078DB715-B364-3FF9-8837-4CDD75BCB013 + 359296
44  CoreFoundation                      0x000000019c695640 23E0FFA8-EB28-3E64-B1BB-054C983F6599 + 644672
45  CoreFoundation                      0x000000019c695540 23E0FFA8-EB28-3E64-B1BB-054C983F6599 + 644416
46  CoreFoundation                      0x000000019c694888 23E0FFA8-EB28-3E64-B1BB-054C983F6599 + 641160
47  CoreFoundation                      0x000000019c68ee40 23E0FFA8-EB28-3E64-B1BB-054C983F6599 + 618048
48  CoreFoundation                      0x000000019c68e600 CFRunLoopRunSpecific + 572
49  GraphicsServices                    0x000000019f1a7598 GSEventRunModal + 160
50  UIKitCore                           0x00000001c705db98 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 10369944
51  UIKitCore                           0x00000001c7063148 UIApplicationMain + 164
52  libswiftUIKit.dylib                 0x00000001b3fa27a4 $s5UIKit17UIApplicationMainys5Int32VAD_SpySpys4Int8VGGSgSSSgAJtF + 100
53  RealmCrash                          0x000000010098aaec $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ + 120
54  RealmCrash                          0x000000010098aa64 $s10RealmCrash11AppDelegateC5$mainyyFZ + 48
55  RealmCrash                          0x000000010098ab30 main + 32
56  libdyld.dylib                       0x000000019c1225fc 5236862C-1081-3967-BC6E-1454D959AE7B + 9724!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.2020-09-20 20:35:33.019706-0400 RealmCrash[1087:1010753] /Users/andrewbarba/Library/Developer/Xcode/DerivedData/RealmCrash-gnivnywwxrjnahdiuqxautfmueui/SourcePackages/checkouts/realm-core/src/realm/util/file.cpp:1040: [realm-core-6.0.26] Assertion failed: err == EEXIST with (err) =  [1]
0   RealmCrash                          0x00000001011135c8 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 28
1   RealmCrash                          0x0000000101113990 _ZN5realm4util19terminate_with_infoEPKcS2_lS2_OSt16initializer_listINS0_9PrintableEE + 316
2   RealmCrash                          0x0000000100a60a7c _ZN5realm4util19terminate_with_infoIJRiEEEvPKciS4_S4_DpOT_ + 132
3   RealmCrash                          0x00000001010d6b90 _ZN5realm4util4File4lockEbb + 856
4   RealmCrash                          0x0000000100e30c9c _ZN5realm4util4File18try_lock_exclusiveEv + 40
5   RealmCrash                          0x0000000100e2ece4 _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 1084
6   RealmCrash                          0x0000000100e322ec _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 288
7   RealmCrash                          0x0000000100e38450 _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 176
8   RealmCrash                          0x00000001009dc5d8 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 916
9   RealmCrash                          0x00000001009db7bc _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 68
10  RealmCrash                          0x00000001009db5d8 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 668
11  RealmCrash                          0x0000000100acc200 _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 176
12  RealmCrash                          0x0000000100c07fd8 +[RLMRealm realmWithConfiguration:queue:error:] + 1796
13  RealmCrash                          0x0000000100c3a3a8 $sSo8RLMRealmC13configuration5queueABSo0A13ConfigurationC_So012OS_dispatch_C0CSgtKcfCTO + 156
14  RealmCrash                          0x0000000100c6cedc $s10RealmSwift0A0V5queueACSo012OS_dispatch_C0CSg_tKcfC + 152
15  RealmCrash                          0x000000010098a1b0 $s10RealmCrash11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0k6LaunchJ3KeyaypGSgtF + 112
16  RealmCrash                          0x000000010098a6d8 $s10RealmCrash11AppDelegateC11application_29didFinishLaunchingWithOptionsSbSo13UIApplicationC_SDySo0k6LaunchJ3KeyaypGSgtFTo + 212
17  UIKitCore                           0x00000001c705a2e8 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 10355432
18  UIKitCore                           0x00000001c705c1b4 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 10363316
19  UIKitCore                           0x00000001c7061830 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 10385456
20  UIKitCore                           0x00000001c685fa70 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 1989232
21  UIKitCore                           0x00000001c6ce0ed4 _UIScenePerformActionsWithLifecycleActionMask + 100
22  UIKitCore                           0x00000001c686057c 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 1992060
23  UIKitCore                           0x00000001c685ffac 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 1990572
24  UIKitCore                           0x00000001c6860390 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 1991568
25  UIKitCore                           0x00000001c685fc40 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 1989696
26  UIKitCore                           0x00000001c6867dc8 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 2022856
27  UIKitCore                           0x00000001c6c05264 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 5812836
28  UIKitCore                           0x00000001c6cf8700 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 244
29  UIKitCore                           0x00000001c6867b60 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 2022240
30  UIKitCore                           0x00000001c66beb3c 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 281404
31  UIKitCore                           0x00000001c66bd5dc 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 275932
32  UIKitCore                           0x00000001c66be788 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 280456
33  UIKitCore                           0x00000001c705fa0c 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 10377740
34  UIKitCore                           0x00000001c6c26db8 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 5950904
35  FrontBoardServices                  0x000000019f773728 078DB715-B364-3FF9-8837-4CDD75BCB013 + 46888
36  FrontBoardServices                  0x000000019f79b038 078DB715-B364-3FF9-8837-4CDD75BCB013 + 208952
37  FrontBoardServices                  0x000000019f780e84 078DB715-B364-3FF9-8837-4CDD75BCB013 + 102020
38  FrontBoardServices                  0x000000019f79ad4c 078DB715-B364-3FF9-8837-4CDD75BCB013 + 208204
39  libdispatch.dylib                   0x00000001024965fc _dispatch_client_callout + 16
40  libdispatch.dylib                   0x0000000102499ac4 _dispatch_block_invoke_direct + 232
41  FrontBoardServices                  0x000000019f7bf9e4 078DB715-B364-3FF9-8837-4CDD75BCB013 + 358884
42  FrontBoardServices                  0x000000019f7bf6ac 078DB715-B364-3FF9-8837-4CDD75BCB013 + 358060
43  FrontBoardServices                  0x000000019f7bfb80 078DB715-B364-3FF9-8837-4CDD75BCB013 + 359296
44  CoreFoundation                      0x000000019c695640 23E0FFA8-EB28-3E64-B1BB-054C983F6599 + 644672
45  CoreFoundation                      0x000000019c695540 23E0FFA8-EB28-3E64-B1BB-054C983F6599 + 644416
46  CoreFoundation                      0x000000019c694888 23E0FFA8-EB28-3E64-B1BB-054C983F6599 + 641160
47  CoreFoundation                      0x000000019c68ee40 23E0FFA8-EB28-3E64-B1BB-054C983F6599 + 618048
48  CoreFoundation                      0x000000019c68e600 CFRunLoopRunSpecific + 572
49  GraphicsServices                    0x000000019f1a7598 GSEventRunModal + 160
50  UIKitCore                           0x00000001c705db98 846E3B76-0F16-300A-98E6-BB91A6C9A9B9 + 10369944
51  UIKitCore                           0x00000001c7063148 UIApplicationMain + 164
52  libswiftUIKit.dylib                 0x00000001b3fa27a4 $s5UIKit17UIApplicationMainys5Int32VAD_SpySpys4Int8VGGSgSSSgAJtF + 100
53  RealmCrash                          0x000000010098aaec $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ + 120
54  RealmCrash                          0x000000010098aa64 $s10RealmCrash11AppDelegateC5$mainyyFZ + 48
55  RealmCrash                          0x000000010098ab30 main + 32
56  libdyld.dylib                       0x000000019c1225fc 5236862C-1081-3967-BC6E-1454D959AE7B + 9724!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.
```

**Comment by tgoyne** [comment]
That bit of code is only supposed to be used on iOS and not tvOS or watchOS, so there's apparently something wrong with the platform check.

**Comment by AndrewBarba** [comment]
@jsflax @tgoyne Let me know if you have a branch you want me to test. We're trying to get a tvOS 14 build out asap so I will test right away

**Comment by jsflax** [comment]
@AndrewBarba I was able to reproduce the issue. I can confirm the [linked pull request](https://github.com/realm/realm-core/pull/3924) fixes the issue if you want to work off of that branch for now. The next release will contain the fix. Thanks for helping out with the sample code 👍

**Comment by AndrewBarba** [comment]
Awesome thanks for the quick fix! Since that PR is in core, do you have an easy way for me to install via CocoaPods?

**Comment by jsflax** [comment]
I don't believe there is an easy way via Cocoapods– I was testing via Swift Package Manager which makes it fairly simple to checkout a branch even for dependencies. However for Cocoapods, we vendor in realm-core as a binary.

**Comment by AndrewBarba** [comment]
Okay thanks, I'll have to wait until this is updated in master then branch on realm-cocoa then. Sadly not using SPM yet in our main project

**Comment by adamk77** [comment]
Is there a general timeline on when this will be merged to master? I see some new versions have been released since this was addressed but do not see it merged yet. Thanks.

**Comment by sunpooh** [comment]
I have got exactly same issue while running on tvOS 14.
Btw, still didn't fix this issue for cocoa pods?

**Comment by jsflax** [comment]
@sunpooh What version of Realm are you using?

**Comment by sunpooh** [comment]
Realm version updated to 10.0, after I use this version, it's error disappeared.
Thank you.
