### ISSUE TITLE
Stable 3% (!!!) crashes realm::Allocator::translate_less_critical(realm::Allocator::RefTranslation*, unsigned long) const + 68

### ISSUE THREAD

**Issue by igorvoytovich** [realm/realm-cocoa#7175]
## Goals
Realm crash free 99.N%

## Expected Results
Realm crash free 99.N%

## Actual Results
Realm crash free 97%

## Steps for others to Reproduce
It is hard to reproduce it internally, because it's random crashes.

## Code Sample
- **All** Realm transactions(writes) from **custom serial GCD queue** within **autoreleasepool**. 
- New Realm instance each time.

`let realmWriteQueue = DispatchQueue(label: "realmWriteQueue")`

```
realmWriteQueue.async {
      autoreleasepool {
          do {
             let realm = try Realm(configuration: ...)
             try realm.write { //all writes ALWAYS here }
          } catch {}
      }
}
```
## Stack trace:
![photo_2021-03-13 13 30 10](https://user-images.githubusercontent.com/47663430/111035930-5afb3100-8425-11eb-8885-8f5b98fe03d1.jpeg)

![photo_2021-03-13 18 06 57](https://user-images.githubusercontent.com/47663430/111036247-f6d96c80-8426-11eb-82d1-9279c1b68e90.jpeg)

![photo_2021-03-13 18 06 54](https://user-images.githubusercontent.com/47663430/111036248-f8a33000-8426-11eb-9be9-a1f3b5422df3.jpeg)

We started seeing these crashes under heavy loads with very active database writes. Reproduced by 3 percent of users.

Realm framework version: **10.5.0**
Xcode version: **12.4**

iOS/OSX version: **iOS 14.4**

Dependency manager + version: **CocoaPods 1.10.1**

**Comment by MonkeyRunHq** [comment]
After upgrading to version **10.7.2**, the problem still persists. Any help here?

**Comment by igorvoytovich** [comment]
After upgrading to version **10.7.2**, the problem still persists. Any help here?

**Comment by finnschiermer** [comment]
@igorvoytovich : Thanks for reporting. It appears to be a duplicate of: https://github.com/realm/realm-core/issues/4514, please direct further comments there.

If you do not believe it to be a duplicate, please reopen.

**Comment by MonkeyRunHq** [comment]
@finnschiermer Thank you for your response. Our crash is not related to SwiftUI in any way. I'll reopen issue.

**Comment by igorvoytovich** [comment]
@finnschiermer Thank you for your response. Our crash is not related to SwiftUI in any way. I'll reopen issue.

**Comment by finnschiermer** [comment]
@igorvoytovich It's likely the same problem anyhow (I don't think swiftui is material to the other problem either), but I'm reopening for now.

**Comment by igorvoytovich** [comment]
@finnschiermer thanks. If you need any additional information please feel free to ask. We are really looking forward to solving this problem and will send the app update as soon as it is resolved.

**Comment by jpstern** [comment]
FWIW - we rolled back to 4.3.2, which was the version we used before seeing these crashes and it's completely gone.

We were previously seeing 100-4000 instances of this crash daily depending on app usage.

**Comment by igorvoytovich** [comment]
@jpstern thanks for sharing this information. At the moment we have the same situation, more than 3000 crashes per day. 
Could you please tell me if it is safe to rollback from version 10.7.2 to 4.3.2? That is, they are fully compatible and users should not have incompatibility problems?

**Comment by jpstern** [comment]
We force deleted the realm file to prevent rollback issues.  The files aren't compatible so your users will get a crash if you try to just rollback

**Comment by jpstern** [comment]
For the realm team - we were ultimately able to reliably reproduce the crash by running sustained very high volume concurrent writes.  Not necessarily a realistic real world scenario, but it was the only way to get the crash to happen.  

It's possible low RAM is a factor for the the RLMRealm being autoreleased during a write transaction.  A noticeable percentage of the crashes showed low RAM on Crashlytics.

**Comment by igorvoytovich** [comment]
@jpstern thank you very much for the information.

@finnschiermer @tgoyne Since the current version is not production-ready, could you tell if we should wait for this problem to be fixed, or would it be more correct to roll back to the old version (4.3.2, for example, as mentioned above)? Thanks.

**Comment by finnschiermer** [comment]
We run massive competing writes periodically as well and with much larger realm files, but haven't hit this issue, so there has to be more to it. Perhaps running low on memory is an important part of this.

**Comment by finnschiermer** [comment]
@igorvoytovich We are actively investigating this issue, and I hope to be able to have an answer to your question (about wait or roll back) next week.

**Comment by igorvoytovich** [comment]
@finnschiermer thank you very much, I really appreciate it. Please feel free to contact me in case of any questions.

**Comment by igorvoytovich** [comment]
@finnschiermer @tgoyne Hello guys! We left the phone connected to Xcode overnight, and we were able to catch this crash. Below I attach a screenshot of the crash itself from Xcode:

![Screen Shot 2021-03-22 at 10 12 56 AM](https://user-images.githubusercontent.com/47663430/111959631-64585d80-8af7-11eb-888c-7d380800d7d8.png)

I hope this information will be useful to you. Thanks.

**Comment by finnschiermer** [comment]
@igorvoytovich FYI we have a tentative fix in development. You can follow it here: https://github.com/realm/realm-core/pull/4534

**Comment by finnschiermer** [comment]
The fix is about how we handle an error condition when we're close to running out of memory. Likely implication: even if we fix this error, your app may fail shortly after, in a different way, due to the same underlying problem: using too much memory. You might be able to investigate this problem without waiting for our fix.

**Comment by igorvoytovich** [comment]
@finnschiermer 

Thanks for your reply.

I'm pretty sure lack of memory is not the reason in our situation. As you can see in the crash screenshot above, our application uses memory efficiently and in total 100 MB was used.

Please correct me if I'm wrong.

**Comment by finnschiermer** [comment]
Thx. That is obviously an indication that the fix may not address your error. We took the clue from @jpstern who commented about low memory higher in this issue. Perhaps we're dealing with two different issues then.

**Comment by igorvoytovich** [comment]
@finnschiermer 

Then I think maybe we should rollback to some old version to check if there will be a problem there?
For example, version 5.5.0 (https://github.com/realm/realm-cocoa/blob/master/CHANGELOG.md#550-release-notes-2020-10-12).

We have no options why this problem may arise and what to do with it, for all metrics Realm works well and quickly.

I can describe in more detail how we use Realm, maybe this can help somehow:

- All Realm transactions(writes) are from custom serial GCD queue within autoreleasepool. New Realm instance each time.
- All Realm reads are from Main thread.
- We actively use collection writes, like: 

    `someResults.setValue(..., forKey: ...)`

For example, we have N messages (ChatMessage) from user A, when we receive new user A model from backend, we save this user to Realm and update all the messages from this user (using above KV method) to have new actual user object. 
By the way, does this function have limitations on array length? We couldn't find this in the documentation. 

- We do all this on the custom queue mentioned above, and after that we refresh the Realm on the main thread using the **.refresh()** function to get the actual data on the main thread.

- We actively use Realm results notifications in many places.

**Comment by tgoyne** [comment]
It sounds like It sounds like https://github.com/realm/realm-core/pull/4534 is unlikely to help you (and if you were actually hitting the problem it fixes it wouldn't help much; gracefully reporting an error rather than crashing still usually doesn't leave the app in a working state). That's unsurprising as it was basically just a blind stab at finding a problem and fixing the first thing I found. I will keep digging for more potential things. Any more information you can provide about what's scenarios cause problems would help, but I don't have any specific suggestions.

> For example, we have N messages from user A, when we receive new user A model from backend, we save this user to Realm and update all the messages from this user (using above KV method) to have new actual user object. By the way, does this function have limitations on array(results) length? We couldn't find this in the documentation.

The big advantage of this function over a manual loop is that it mostly avoids allocating any temporary objects. In theory it should work for arbitrarily large arrays.

**Comment by igorvoytovich** [comment]
@tgoyne 

Thanks for your reply.

We had suspicions about this particular function, that is, we use it in several places, and often the update can affect up to several hundred objects (for example, messages in our case) at a time.

There are also suspicions that the forced refresh of Realm can affect, since we do it quite often. But, as far as I know, and as we understood from the documentation, this function is called on each RunLoop cycle anyway, that's why we use it so freely and haven't tried ThreadSafeReferences. 

Perhaps we should redo the code from forced refreshes of Realm to use ThreadSafeReferences, in cases where we receive and save an object in another thread and immediately we need to work with it in the main thread? How do you think?

**Comment by tgoyne** [comment]
Explicitly calling `refresh()` will block the main thread until the notification worker is done processing a write, while otherwise we delay notifying the main thread until that's done so that it can continue to process user interaction. It otherwise behaves identically to automatic refreshes.

Resolving a ThreadSafeReference which was created at a later version than the local Realm is at just calls `refresh()` internally. It's theoretically faster than looking up the object by PK again but it's a negligible difference. TSR<Object> is mostly only interesting for object types without primary keys.

**Comment by tgoyne** [comment]
You've only seen this on iOS devices and not in the simulator, right? The xover mapping logic is full of atomics that *look* right, but a bug in them which is hidden on x86 by the stricter memory model would make a lot of sense.

**Comment by igorvoytovich** [comment]
@tgoyne 

Yes, we see this crash on real devices. On our side, we were able to reproduce it on iPhone SE 2020, iOS 14.4

**Comment by igorvoytovich** [comment]
@tgoyne 
Thank you very much for your detailed explanations. I really appreciate it.

**Comment by tgoyne** [comment]
One thing I notice is that one of the stack traces is showing a write transaction being cancelled due to the RLMRealm being deallocated while in a write transaction. Is that a thing you expect to have happening sometimes?

Does the device which reproduced it have free disk space? I doubt that's the problem but just to eliminate it as a possibility...

**Comment by igorvoytovich** [comment]
@tgoyne 

We were able to reproduce this on a test device with over 50GB of free disk space, which we use exclusively for testing our application.

As for RAM memory, according to Xcode, our application consumes no more than 100-110 MB with active use, which is no more than 3-4% according to Xcode analytics.

**Comment by igorvoytovich** [comment]
@tgoyne hello, we caught another crash with a request to report it in the logs. Maybe somehow connected.
Here are screenshots:

![photo_2021-04-05 23 10 21](https://user-images.githubusercontent.com/47663430/113621430-47c63480-9664-11eb-8992-b215a75d2f3b.jpeg)

![photo_2021-04-05 23 10 23](https://user-images.githubusercontent.com/47663430/113622311-7bee2500-9665-11eb-99c1-4f029e8096e9.jpeg)

**Comment by igorvoytovich** [comment]
@tgoyne @finnschiermer 

Hello,

After upgrading to version 10.7.4, the crash now gets a stack like this:
![photo_2021-04-30 21 56 26](https://user-images.githubusercontent.com/47663430/116741575-fb6dda80-a9fe-11eb-83a1-322c726e9f22.jpeg)
![photo_2021-04-30 21 56 28](https://user-images.githubusercontent.com/47663430/116741595-ff99f800-a9fe-11eb-9a27-363e83209dcf.jpeg)

Such a case that the Realm instance deallocates earlier in our case is impossible, since every time we create a new Realm instance inside the serial queue async block within autoreleasepool. Like:

```
let realmWriteQueue = DispatchQueue(label: "realmWriteQueue")

realmWriteQueue.async {
      autoreleasepool {
          do {
             let realm = try Realm(configuration: ...)
             try realm.write { //all writes ALWAYS here }
          } catch {}
      }
}
```

I hope this information will be useful to you.

**Comment by igorvoytovich** [comment]
@tgoyne @finnschiermer 

Hello,

Some time ago we sent a version of the application with RealmSwift v5.5.2 to a limited audience for a test. And I can confirm that this crash is not reproduced on this version of the Realm SDK.

Could you please tell us whether we should wait for some fix or it would be better to transfer all users to the old version of the SDK?

Thanks.

**Comment by therealyou1** [comment]
We are seeing the same problem. Could you please tell if there will be any fix?
@tgoyne @finnschiermer

**Comment by igorvoytovich** [comment]
@tgoyne @finnschiermer 

Hello,

I would like to clarify if there is any progress on this issue?
More than 2 months have passed, and we would like to understand what to do with this next.

Please let me know if you need any additional information, I will gladly provide you with it.

Thanks.

**Comment by ironage** [comment]
Hi @igorvoytovich are you able to reproduce this with cocoa version 10.7.6? I just noticed that the [stack trace](https://github.com/realm/realm-core/pull/4687#issuecomment-839367853) of a bug we fixed is very similar to what you reported [above](https://github.com/realm/realm-cocoa/issues/7175#issuecomment-813626885). This is still a guess, but the conditions of the fixed bug seem to match a couple of the clues in this issue; a sync app advancing or rolling back a transaction which first created a tombstone table (meaning some data shared between sync users was deleted by someone for the first time).

**Comment by igorvoytovich** [comment]
@ironage 

Hello,

Thanks for your message.

Unfortunately I can still reproduce this on 10.7.6.

If I understood you correctly, you are talking about data synchronization between several users, if so, then this is definitely not our case, since we use Realm exclusively locally.

**Comment by ironage** [comment]
@igorvoytovich thanks for testing it out so quickly! I agree, if your app is not using Realm sync then the fix I linked is unrelated.

**Comment by igorvoytovich** [comment]
Hello,

There is another example of the crash step by step:

![Screen Shot 2021-05-22 at 8 43 57 PM](https://user-images.githubusercontent.com/47663430/119236176-a7a66b00-bb3e-11eb-82e7-acff73344e16.png)
![Screen Shot 2021-05-22 at 8 44 18 PM](https://user-images.githubusercontent.com/47663430/119236178-aa08c500-bb3e-11eb-90a2-18c79f5c070f.png)
![Screen Shot 2021-05-22 at 8 44 34 PM](https://user-images.githubusercontent.com/47663430/119236179-abd28880-bb3e-11eb-8d2a-34ee76d2fe3a.png)

**Comment by sxcrim** [comment]
We have the same problem. Are there any updates?
@tgoyne @finnschiermer

**Comment by igorvoytovich** [comment]
@finnschiermer ,

thanks for getting back to me.

We are seeing these crashes on real iPhones. To be more specific: iPhone SE 2, iPhone 11 Pro Max. All on iOS 14.5-14.6.
For development and deployment, we use only Macs with an M1 chip, integration via CocoaPods.

We've tried a bunch of things already, and we can't even imagine where the mistake might be on our side, from our side the code is as simple and predictable as possible.

If you have any questions, please do not hesitate to ask anytime.

By the way, we already use 10.8.0 version of SDK, and the problem still persist.

**Comment by igorvoytovich** [comment]
@tgoyne @finnschiermer 

Hello,

Could you please tell if there is a difference between:

`try realm.write { //Realm work here... }`

and

```
realm.beginWrite()
//Realm work here...
try realm.commitWrite()
```
By the SDK code, I see that the first option calls the second one, with additional error handling, but I am confused by line 257:
<img width="987" alt="Screen Shot 2021-06-27 at 13 48 19" src="https://user-images.githubusercontent.com/47663430/123541676-5f3a2880-d74e-11eb-9bc2-9179b929e041.png">


Considering the fact and as you can see from the screenshots above that we have a lot of problems with the cancelWrite () / cancelWriteTransaction() function, I think this may be somehow related. We will try to replace all work with Realm with the use of the second option for creating a transaction.

I also want to note that there are places in the documentation where the second method is used, but without explanation why and when it is better to use it. Please take a look:

<img width="635" alt="Screen Shot 2021-06-27 at 13 39 44" src="https://user-images.githubusercontent.com/47663430/123541408-25b4ed80-d74d-11eb-9e97-fe94d5cc71d7.png">

Thanks.

**Comment by igorvoytovich** [comment]
We tried beginWrite() and commitWrite() and got the same problem.

We also changed the object schemes a little in order to find out what the problem is, namely, removed the indexed properties. And we got the same crash, but with a new stack trace:

![photo_2021-06-27 17 35 20](https://user-images.githubusercontent.com/47663430/123548600-1a25ee80-d76e-11eb-9dd6-d6c8eda8a7fc.jpeg)
![photo_2021-06-27 17 35 21](https://user-images.githubusercontent.com/47663430/123548601-1c884880-d76e-11eb-877f-3104fcd924c4.jpeg)
![photo_2021-06-27 17 35 22](https://user-images.githubusercontent.com/47663430/123548605-1f833900-d76e-11eb-8430-fa5c5f9b4717.jpeg)
![photo_2021-06-27 17 35 23](https://user-images.githubusercontent.com/47663430/123548608-21e59300-d76e-11eb-9ce2-60623837e787.jpeg)

@tgoyne @finnschiermer I hope this helps somehow

**Comment by igorvoytovich** [comment]
By the way, people had the same problem, but the issue was closed without any changes:

https://github.com/realm/realm-cocoa/issues/6690

**Comment by jsflax** [comment]
@igorvoytovich what does your observation code look like?

**Comment by igorvoytovich** [comment]
@jsflax 
hi, here it is:
![photo_2021-06-27 18 08 08](https://user-images.githubusercontent.com/47663430/123549685-af2ae680-d772-11eb-8fd3-c94f022d8b12.jpeg)
![photo_2021-06-27 18 08 10](https://user-images.githubusercontent.com/47663430/123549688-b225d700-d772-11eb-8ccf-ed7d41eca34b.jpeg)
![photo_2021-06-27 18 08 12](https://user-images.githubusercontent.com/47663430/123549693-b520c780-d772-11eb-8fb6-17262b29028c.jpeg)

**Comment by igorvoytovich** [comment]
![photo_2021-06-27 19 54 47](https://user-images.githubusercontent.com/47663430/123553005-9ece3800-d781-11eb-821c-a84780271583.jpeg)
![photo_2021-06-27 19 54 53](https://user-images.githubusercontent.com/47663430/123553001-9d047480-d781-11eb-8772-ca1ba1cbf56d.jpeg)

I added such a logging function and call it every time after a transaction to Realm. As you can see, the file size grows significantly even when the number of objects does not change. This continues until the application crashes.

What could be the problem?

**Comment by igorvoytovich** [comment]
Reproducable after some time using the app / Realm, here's another example:

![photo_2021-06-27 20 11 27](https://user-images.githubusercontent.com/47663430/123553452-e6ee5a00-d783-11eb-8b8a-cb259a1c90e9.jpeg)

And so it will continue indefinitely, until it takes away all the memory. Realm works as it should for a while, then after something it breaks down and a strong memory growth begins, regardless of the activity of transactions.

**Comment by igorvoytovich** [comment]
@tgoyne @finnschiermer @jsflax 

I can confirm that these problems are not present on RealmSwift 4.3.2.

We checked on the same project, everything that changed is replaced **freeze()** with **detached()** (https://github.com/realm/realm-cocoa/issues/5433#issuecomment-415066361) , because freeze was added after 4.3.2

On this SDK version, Realm works perfectly, without going beyond the size of 1 MB on our data volumes.
![photo_2021-06-27 20 34 05](https://user-images.githubusercontent.com/47663430/123554069-0a66d400-d787-11eb-8338-607c8dd0ac2f.jpeg)

I **beg** you to tell us what to do in this situation, should we wait for any changes? Or should we consider replacing Realm or downgrading to a lower version (4.3.2)?

I hope for your understanding, because due to these problems we are suffering large financial losses and we need to resolve this as soon as possible.

**Comment by jsflax** [comment]
Can you show us where/how you're using `freeze`? Freezing objects uses version pinning which can greatly increase the size of a Realm file.

**Comment by igorvoytovich** [comment]
We save users objects and collect the array on another thread (realmWriteThread) and send it to the main thread in this way.

![Screen Shot 2021-06-27 at 8 47 19 PM](https://user-images.githubusercontent.com/47663430/123554484-e6a48d80-d788-11eb-930e-863b20f8606a.png)

(users - [User] array of manager objects, managed by Realm on realmWriteQueue)

The fact is that Realm retains its size between application restarts. I thought that freezed is just an Unmanager copy of realm object, how can it affect Realm size?

@jsflax

**Comment by igorvoytovich** [comment]
@jsflax 

Seems like you are right. After replacing **freeze()** with **detached()** (https://github.com/realm/realm-cocoa/issues/5433#issuecomment-415066361) I can not reproduce the problem for now. So whats the point of using freeze() then?

I will monitor for a few hours and will get back here with results.

By the way, is it normal that on 10.8.1 objects with same schema is 30-40% larger than on 4.3.2?

**Comment by jsflax** [comment]
Freeze is used for when you want an immutable value that is easily transferable between threads. It's not meant to be used for longstanding operations, especially off of the main thread.

We see most users using freeze as a means of diffing values (a necessity since Realm types are always 'live'). If you do not need that kind of behaviour, I would consider alternatives to what you are doing. Holding onto frozen values should be done with caution.

**Comment by igorvoytovich** [comment]
After stopping using **freeze()**, the problem went away. Everything is working perfectly now.
I hope that our experience will help other people who have faced similar problems.


@finnschiermer @tgoyne @jsflax @ironage 
I am very grateful to you for your time and help. I really appreciate that.

**Many thanks! Best wishes to you!**

**Comment by finnschiermer** [comment]
@igorvoytovich I'm happy it has solved your problem. From my perspective there is still a problem to fix: whether you use freeze as intended or not, we shouldn't have a crash in the allocator.
